### ISSUE TITLE
add release on github

### ISSUE THREAD

**Issue by JoshiiSinfield** [dyladan/terraform-provider-dynatrace#5]
Hi @dyladan ,

Is it possible for you to add a release here on github, to be able to download straight from a link rather than having to build it?

Cheers,
Josh

**Comment by dyladan** [comment]
@JoshiiSinfield I would like to eventually release it if it ever becomes useful. Currently not enough of the API surface is covered to make this worth using in my opinion, and adding a "release" would be confusing to people.

**Comment by JoshiiSinfield** [comment]
Cheers for getting back to me!

All I currently want it for is to add the aws account credentials when a new AWS account is created, which this looks like it'll do just fine?

I was hoping for just a 0.0.1 release, rather than having to store the binary myself somewhere.

I understand what you're saying, but 0.0.1 doesn't need to be complete ;)

**Comment by JoshiiSinfield** [comment]
ah maybe not just yet ... return nil won't cut it! 

I'll try find time to assist and submit a PR if you're good with that?

**Comment by dyladan** [comment]
That would be great. Unfortunately I don't have a ton of time to work on
this these days, but I am hoping it is eventually useful enough to release.
